version: "3"

services: 
    web:
        container_name: flaskblog
        restart: always
        build: .
        env_file: .env
        ports: 
            - "9000:5000"
        depends_on: 
            - database

    database:
        container_name: blogmysql
        restart: always
        image: mysql:5.7
        ports: 
            - "3307:3306"
        volumes: 
            - mysqldata:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=12345678
            - MYSQL_DATABASE=sky_blog
            - MYSQL_USER=root
            - MYSQL_PASSWORD=12345678
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
        ]

volumes: 
    mysqldata: